[package]
name = "vanity_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
ed25519-dalek = "2.1.1"
rand = "0.8"
rayon = "1.10"
bs58 = "0.4"
num-format = "0.4"
logfather = "0.2.6"
rust-gpu-tools = { version = "0.8", features = ["cuda"] }  # GPU acceleration
indicatif = "0.17.7"  # Progress display
