[package]
name = "solana_vanity"
version = "0.3.4"
edition = "2021"
authors = [
    "Your Name <your_email@example.com>",
]
license = "MIT OR Apache-2.0"
description = "A *bLaZinGlY fAsT* tool for grinding vanity addresses on Solana"

[features]
gpu = ["cc"]

[dependencies]
ocl = "0.20.0"
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
num-format = "0.4"
clap = { version = "4.5", features = ["derive"] }
rand = "0.8"
rayon = "1.10"
bs58 = { version = "0.5", features = ["check"] }
logfather = "0.2.6"

# GPU-related dependencies
ocl = { version = "0.19", optional = true }

[build-dependencies]
cc = { version = "1.0.98", optional = true }
