[package]
name = "solana_vanity"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
ed25519-dalek = "2.1.1"
rand = "0.8"
rayon = "1.10"
bs58 = { version = "0.5", features = ["check"] }
num-format = "0.4"
logfather = "0.2.6"
