[package]
name = "solana_vanity"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "solana_vanity"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
ocl = "0.19.3"
rand = "0.8"
rayon = "1.10"
cc = "1.0"
  
[features]
gpu = []

[profile.release]
lto = "fat"
codegen-units = 1
