[dependencies]
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
serde_json = "1.0"
num-format = "0.4"
rayon = "1.10"
bs58 = { version = "0.5", features = ["check"] }
logfather = "0.2.6"
rand = "0.8"
clap = { version = "4.5", features = ["derive"] }
